services:
  discovery-service:
    build: ./EurekaServer
    image: halimtrabelsi/discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    hostname: discovery
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - unihub-network

  mysql-db:
    image: mysql:5.6
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=gestionStock_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - ./local_data:/var/lib/mysql
    networks:
      - unihub-network


  gateway-service:
    build: ./Gateway
    image: halimtrabelsi/gateway-service:latest
    container_name: gateway-service
    ports:
      - "8093:8093"
    hostname: gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - spring.cloud.gateway.routes[0].id=GESTIONSTOCK
      - spring.cloud.gateway.routes[0].uri=http://stock-service:8089
      - spring.cloud.gateway.routes[0].predicates[0]=Path=/api/stocks/**
      - spring.cloud.gateway.routes[1].id=NEW_ROUTE
      - spring.cloud.gateway.routes[1].uri=http://stock-service:8089
      - spring.cloud.gateway.routes[1].predicates[0]=Path=/api/stocks/**
    depends_on:
      discovery-service:
        condition: service_healthy
      mysql-db:
        condition: service_healthy
    networks:
      - unihub-network

  stock-service:
    build: ./GESTIONSTOCK
    image: halimtrabelsi/stock-service:latest
    container_name: stock-service
    ports:
      - "8089:8089"
    hostname: stock-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/gestionStock_db?autoReconnect=true&useSSL=false
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      discovery-service:
        condition: service_healthy
      mysql-db:
        condition: service_healthy
    networks:
      - unihub-network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: keycloak
    command: start-dev --http-port=8180
    ports:
      - "8180:8180"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8180"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - unihub-network

networks:
  unihub-network:
    name: unihub-network

volumes:
  mysql-data:
    driver: local